### ISSUE TITLE
extracting results

### ISSUE THREAD

**Issue by XkhldY** [reiinakano/xcessiv#21]
how ca i extract the predictions generated ???

**Comment by reiinakano** [comment]
Hi @XkhldY,  I am currently working on a feature to extract the full stacked ensemble as a python package so you can import it and use it as a standalone base learner that can generate predictions on new data. Unfortunately, right now there is no way to do this and you are only given the ensemble's metrics during cross validation.

**Comment by XkhldY** [comment]
If I can help??

**Comment by reiinakano** [comment]
Hi @XkhldY , I've already taken care of the issue with PR #22 . Please upgrade to version 0.3.5 and look at the documentation to find how you can extract the ensemble and use it to generate predictions on new and unseen data.

If you would like to help, Xcessiv still needs a lot of work to be done. For example, Xcessiv really needs a lot more unit tests (So far, I've followed bad practice and neglected them..). 

You can also help out with Issue #15 if you want to start off small. Thank you for offering to help! :)
