### ISSUE TITLE
Can't Use

### ISSUE THREAD

**Issue by xnmp** [reiinakano/xcessiv#36]
Sorry for what is no doubt a stupid question:

I've started Redis via `redis-server`. It says it's running on port 6379. Then I run `xcessiv`, but it takes me to a page that's not found. `The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.`. Any idea what I can do? I'm really eager to use Xcessiv.

**Comment by reiinakano** [comment]
Could you copy the logs on your terminal when you run xcessiv? Also, what page is opening? Localhost:1994?

**Comment by xnmp** [comment]
Yeah it's Localhost:1994. This is the log:

```
/home/user/Documents/Analysis/XcessivProjects
09:44:47 RQ worker 'rq:worker:syd-user-d.15386' started, version 0.8.0
09:44:47 Cleaning registries for queue: default
09:44:47 
09:44:47 *** Listening on default...
Created new window in existing browser session.
::ffff:127.0.0.1 - - [2017-06-15 09:44:47] "GET / HTTP/1.1" 404 342 0.019557
^CKeyboardInterrupt
Thu Jun 15 09:45:07 2017
09:45:07 Warm shut down requested
Process Process-1:
09:45:07 Cold shut down
```

**Comment by reiinakano** [comment]
Wow, that is odd.  Everything seems to start fine, except it can't find index.html.

I'm not sure how to resolve this... Can you try reinstalling? Maybe somehow the static files got corrupted?

**Comment by xnmp** [comment]
I'm using a virtual environment, could that be a problem?

**Comment by reiinakano** [comment]
To test it out, I actually tried a virtual env. Sadly, I couldn't reproduce your bug :(

**Comment by reiinakano** [comment]
Hi @xnmp , have you resolved this issue?
