### ISSUE TITLE
Valid values for metric to optimise in bayesian optimisation?

### ISSUE THREAD

**Issue by Data-drone** [reiinakano/xcessiv#39]
Is there a list of valid metric_to_optimise for Bayesian Optimisation?

I am using sklearn mean_squared_regression for my base learning but when I enter that into the Bayesian Optimisation menu under metric_to_optimise I get: 

    assert module.metric_to_optimize in automated_run.base_learner_origin.metric_generators
    AssertionError

**Comment by reiinakano** [comment]
Hi there! The valid metric to optimize should actually be a string that corresponds to a metric generator configured in your base learner. For example, if you have a Random Forest and you set it with metric generators "Accuracy", "F1 Score", "My Awesome Metric", the valid values for metric_to_optimize are the strings "Accuracy", "F1 Score", and "My Awesome Metric".
