### ISSUE TITLE
The _BasePipeline in exported Python script should be _BaseComposition

### ISSUE THREAD

**Issue by Mithrillion** [reiinakano/xcessiv#50]
Since scitkit-learn 0.19.x, the base class for Pipeline has changed to _BaseComposition.
https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/pipeline.py
When using the generated code for training, it raises a name-not-found error on newer versions of sklearn.
At the moment, an easy workaround is to change two instances of the word manually in the generated script.

**Comment by reiinakano** [comment]
Thanks for pointing this out! I'll get on a fix right away.
