### ISSUE TITLE
'dict_keys' object does not support indexing

### ISSUE THREAD

**Issue by KhaledSharif** [reiinakano/xcessiv#6]
On lines 306 and 309 of [views.py](https://github.com/reiinakano/xcessiv/blob/master/xcessiv/views.py), trying to index a dictionary keys object will fail on Python 3 and result in a server error. The fix is simple: change all occurrences of 

`base_learner_origin.validation_results.keys()[0]`

to

`list(base_learner_origin.validation_results.keys())[0]`

**Comment by reiinakano** [comment]
Thanks for catching this! I haven't written any tests yet, and I really should.. Fixed in release v0.1.2
